### ISSUE TITLE
Optgroup doesn't work.

### ISSUE THREAD

**Issue by tiagoargolo** [leonardovff/htmlSelectTree#3]
I'm trying to use optgroup, but it seems to be ignored by the select element. All options are displayed like there was no optgroup. 

However, if I remove the "selectTree" class, everything works fine.

Thanks in advance.

**Comment by leonardovff** [comment]
When it was developed, there was no requirement to keep "opt-group" in the options, the next version will! @tiagoargolo

**Comment by tiagoargolo** [comment]
Thank you
